#include "BIS_AddonInfo.hpp"
class CfgPatches
{
	class lbtt_Vest_config
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]={};
	};
};
class CfgMods
{
	class Mod_Base;
	class spec4_gear: Mod_Base
	{
		name="Spec4Gear";
		author="Cunico";
		picture="\lbt\data\images\logo.paa";
		logo="\lbt\data\images\logo.paa";
		logoOver="\lbt\data\images\exp.paa";
		logoSmall="\lbt\data\images\logo_small.paa";
		tooltip="Spec4Gear";
		tooltipOwned="Special Operations Gear";
		action="https://www.patreon.com/cunico";
		actionName="Support";
		overview="Spec4gear allows you to look highspeed with modern gear so you can pew pew the bad guys";
		overviewPicture="\lbt\data\images\logo.paa";
		overviewText="Spec4Gear";
		hideName=1;
		hidePicture=0;
	};
	author="cunico";
	timepacked="1476636984";
};
class CfgWeapons
{
	class Default;
	class ItemCore: Default
	{
	};
	class UniformItem: ItemCore
	{
		class ItemInfo;
	};
	class InventoryItem_Base_F;
	class HeadgearItem: InventoryItem_Base_F
	{
		class ItemInfo;
		class HeadgearItem;
	};
	class VestItem: ItemCore
	{
		class ItemInfo;
	};
	class Uniform_Base: ItemCore
	{
		class ItemInfo;
	};
	class Vest_Camo_Base;
	class lbt_pouchless_coy: Vest_Camo_Base
	{
		author="Cunico";
		dlc="Spec4_Gear";
		allowedSlots[] = {901}; 
		scope=2;
		displayName="[S4] LBT COY (Pouchless)";
		picture="\lbt\UI\lbtcoy_ca.paa";
		model="\lbt\pouchless";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_coy.paa",
			"lbt\Data\gear_coy.paa",
			"insignia"
		};
		class ItemInfo: VestItem
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_coy.paa",
				"lbt\Data\gear_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\pouchless";
			containerClass="Supply160";
			mass=50;
			class HitpointsProtectionInfo
			{
				class Chest
				{
					hitpointName="HitChest";
					armor=16;
					passThrough=0.30000001;
				};
				class Diaphragm
				{
					hitpointName="HitDiaphragm";
					armor=16;
					passThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=16;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	
	class lbt_pouchless_od: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT OD (Pouchless)";
		picture="\lbt\UI\lbtod_ca.paa";
		model="\lbt\pouchless";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_co.paa",
			"lbt\Data\gear_co.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_co.paa",
				"lbt\Data\gear_co.paa",
				"insignia"
			};
			uniformModel="\lbt\pouchless";
		};
	};
	class lbt_pouchless_aor1: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT AOR1 (Pouchless)";
		picture="\lbt\UI\lbtaor1_ca.paa";
		model="\lbt\pouchless";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_aor1.paa",
			"lbt\Data\gear_aor1.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_aor1.paa",
				"lbt\Data\gear_aor1.paa",
				"insignia"
			};
			uniformModel="\lbt\pouchless";
		};
	};
	class lbt_pouchless_aor2: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT AOR2 (Pouchless)";
		picture="\lbt\UI\lbtaor2_ca.paa";
		model="\lbt\pouchless";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_aor2.paa",
			"lbt\Data\gear_aor2.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_aor2.paa",
				"lbt\Data\gear_aor2.paa",
				"insignia"
			};
			uniformModel="\lbt\pouchless";
		};
	};
	class lbt_pouchless_mc: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT MC (Pouchless)";
		picture="\lbt\UI\lbtmc_ca.paa";
		model="\lbt\pouchless";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_mc.paa",
			"lbt\Data\gear_mc.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_mc.paa",
				"lbt\Data\gear_mc.paa",
				"insignia"
			};
			uniformModel="\lbt\pouchless";
		};
	};
	class lbt_tl_mc: Vest_Camo_Base
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT MC (Team Lead)";
		picture="\lbt\UI\lbtmc_ca.paa";
		containerClass="Supply160";
		model="\lbt\tl";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_mc.paa",
			"lbt\Data\gear_mc.paa",
			"lbt\Data\radio_mc.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa"
		};
		class ItemInfo: VestItem
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_mc.paa",
				"lbt\Data\gear_mc.paa",
				"lbt\Data\radio_mc.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_coy.paa"
			};
			uniformModel="\lbt\tl";
			containerClass="Supply160";
			mass=50;
			class HitpointsProtectionInfo
			{
				class Chest
				{
					hitpointName="HitChest";
					armor=16;
					passThrough=0.30000001;
				};
				class Diaphragm
				{
					hitpointName="HitDiaphragm";
					armor=16;
					passThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=16;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	class lbt_tl_coy: lbt_tl_mc
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT COY (Team Lead)";
		picture="\lbt\UI\lbtcoy_ca.paa";
		model="\lbt\tl";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_coy.paa",
			"lbt\Data\gear_coy.paa",
			"lbt\Data\radio_coy.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_coy.paa",
				"lbt\Data\gear_coy.paa",
				"lbt\Data\radio_coy.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\tl";
		};
	};	
	class lbt_tl_od: lbt_tl_mc
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT OD (Team Lead)";
		picture="\lbt\UI\lbtod_ca.paa";
		model="\lbt\tl";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_co.paa",
			"lbt\Data\gear_co.paa",
			"lbt\Data\radio_co.paa",
			"lbt\Data\grenade_co.paa",
			"lbt\Data\pouch_co.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_co.paa",
				"lbt\Data\gear_co.paa",
				"lbt\Data\radio_co.paa",
				"lbt\Data\grenade_co.paa",
				"lbt\Data\pouch_co.paa",
				"insignia"
			};
			uniformModel="\lbt\tl";
		};
	};
	class lbt_tl_aor1: lbt_tl_mc
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT AOR1 (Team Lead)";
		picture="\lbt\UI\lbtaor1_ca.paa";
		model="\lbt\tl";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_aor1.paa",
			"lbt\Data\gear_aor1.paa",
			"lbt\Data\radio_aor1.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_aor1.paa",
				"lbt\Data\gear_aor1.paa",
				"lbt\Data\radio_aor1.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\tl";
		};
	};
	class lbt_tl_aor2: lbt_tl_mc
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT AOR2 (Team Lead)";
		picture="\lbt\UI\lbtaor2_ca.paa";
		model="\lbt\tl";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_aor2.paa",
			"lbt\Data\gear_aor2.paa",
			"lbt\Data\radio_aor2.paa",
			"lbt\Data\grenade_co.paa",
			"lbt\Data\pouch_co.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_aor2.paa",
				"lbt\Data\gear_aor2.paa",
				"lbt\Data\radio_aor2.paa",
				"lbt\Data\grenade_co.paa",
				"lbt\Data\pouch_co.paa",
				"insignia"
			};
			uniformModel="\lbt\tl";
		};
	};
	class lbt_operator_coy: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT COY (Operator)";
		picture="\lbt\UI\lbtcoy_ca.paa";
		model="\lbt\operator";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_coy.paa",
			"lbt\Data\gear_coy.paa",
			"lbt\Data\radio_coy.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_coy.paa",
				"lbt\Data\gear_coy.paa",
				"lbt\Data\radio_coy.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\operator";
		};
	};
	
	class lbt_operator_od: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT OD (Operator)";
		picture="\lbt\UI\lbtod_ca.paa";
		model="\lbt\operator";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_co.paa",
			"lbt\Data\gear_co.paa",
			"lbt\Data\radio_co.paa",
			"lbt\Data\grenade_co.paa",
			"lbt\Data\pouch_co.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_co.paa",
				"lbt\Data\gear_co.paa",
				"lbt\Data\radio_co.paa",
				"lbt\Data\grenade_co.paa",
				"lbt\Data\pouch_co.paa",
				"insignia"
			};
			uniformModel="\lbt\operator";
		};
	};
	class lbt_operator_aor1: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT AOR1 (Operator)";
		picture="\lbt\UI\lbtaor1_ca.paa";
		model="\lbt\operator";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_aor1.paa",
			"lbt\Data\gear_aor1.paa",
			"lbt\Data\radio_aor1.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_aor1.paa",
				"lbt\Data\gear_aor1.paa",
				"lbt\Data\radio_aor1.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\operator";
		};
	};
	class lbt_operator_aor2: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT AOR2 (Operator)";
		picture="\lbt\UI\lbtaor2_ca.paa";
		model="\lbt\operator";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_aor2.paa",
			"lbt\Data\gear_aor2.paa",
			"lbt\Data\radio_aor2.paa",
			"lbt\Data\grenade_co.paa",
			"lbt\Data\pouch_co.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_aor2.paa",
				"lbt\Data\gear_aor2.paa",
				"lbt\Data\radio_aor2.paa",
				"lbt\Data\grenade_co.paa",
				"lbt\Data\pouch_co.paa",
				"insignia"
			};
			uniformModel="\lbt\operator";
		};
	};
	class lbt_operator_mc: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT MC (Operator)";
		picture="\lbt\UI\lbtmc_ca.paa";
		model="\lbt\operator";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_mc.paa",
			"lbt\Data\gear_mc.paa",
			"lbt\Data\radio_mc.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_mc.paa",
				"lbt\Data\gear_mc.paa",
				"lbt\Data\radio_mc.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\operator";
		};
	};
	class lbt_weapons_coy: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT COY (Weapons)";
		picture="\lbt\UI\lbtcoy_ca.paa";
		model="\lbt\weapons";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5",
			"Camo6",
			"Camo7"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_coy.paa",
			"lbt\Data\gear_coy.paa",
			"lbt\Data\radio_coy.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"lbt\Data\m203_co.paa",
			"lbt\Data\m203_gn.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5",
				"Camo6",
				"Camo7"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_coy.paa",
				"lbt\Data\gear_coy.paa",
				"lbt\Data\radio_coy.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_coy.paa",
				"lbt\Data\m203_co.paa",
				"lbt\Data\m203_gn.paa",
				"insignia"
			};
			uniformModel="\lbt\weapons";
		};
	};
	class lbt_weapons_od: lbt_weapons_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT OD (Weapons)";
		picture="\lbt\UI\lbtod_ca.paa";
		model="\lbt\weapons";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5",
			"Camo6",
			"Camo7"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_co.paa",
			"lbt\Data\gear_co.paa",
			"lbt\Data\radio_co.paa",
			"lbt\Data\grenade_co.paa",
			"lbt\Data\pouch_co.paa",
			"lbt\Data\m203_od.paa",
			"lbt\Data\m203_gn_od.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5",
				"Camo6",
				"Camo7"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_co.paa",
				"lbt\Data\gear_co.paa",
				"lbt\Data\radio_co.paa",
				"lbt\Data\grenade_co.paa",
				"lbt\Data\pouch_co.paa",
				"lbt\Data\m203_od.paa",
				"lbt\Data\m203_gn_od.paa",
				"insignia"
			};
			uniformModel="\lbt\weapons";
			containerClass="Supply160";
			mass=50;
		};
	};
	class lbt_weapons_aor1: lbt_weapons_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT AOR1 (Weapons)";
		picture="\lbt\UI\lbtaor1_ca.paa";
		model="\lbt\weapons";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5",
			"Camo6",
			"Camo7"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_aor1.paa",
			"lbt\Data\gear_aor1.paa",
			"lbt\Data\radio_aor1.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"lbt\Data\m203_co.paa",
			"lbt\Data\m203_gn.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5",
				"Camo6",
				"Camo7"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_aor1.paa",
				"lbt\Data\gear_aor1.paa",
				"lbt\Data\radio_aor1.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_coy.paa",
				"lbt\Data\m203_co.paa",
				"lbt\Data\m203_gn.paa",
				"insignia"
			};
			uniformModel="\lbt\weapons";
			containerClass="Supply160";
			mass=50;
		};
	};
	class lbt_weapons_aor2: lbt_weapons_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT AOR2 (Weapons)";
		picture="\lbt\UI\lbtaor2_ca.paa";
		model="\lbt\weapons";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5",
			"Camo6",
			"Camo7"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_aor2.paa",
			"lbt\Data\gear_aor2.paa",
			"lbt\Data\radio_aor2.paa",
			"lbt\Data\grenade_co.paa",
			"lbt\Data\pouch_co.paa",
			"lbt\Data\m203_od.paa",
			"lbt\Data\m203_gn_od.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5",
				"Camo6",
				"Camo7"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_aor2.paa",
				"lbt\Data\gear_aor2.paa",
				"lbt\Data\radio_aor2.paa",
				"lbt\Data\grenade_co.paa",
				"lbt\Data\pouch_co.paa",
				"lbt\Data\m203_od.paa",
				"lbt\Data\m203_gn_od.paa",
				"insignia"
			};
			uniformModel="\lbt\weapons";
		};
	};
	class lbt_weapons_mc: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT MC (Weapons)";
		picture="\lbt\UI\lbtmc_ca.paa";
		model="\lbt\weapons";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5",
			"Camo6",
			"Camo7"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_mc.paa",
			"lbt\Data\gear_mc.paa",
			"lbt\Data\radio_mc.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"lbt\Data\m203_co.paa",
			"lbt\Data\m203_gn.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5",
				"Camo6",
				"Camo7"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_mc.paa",
				"lbt\Data\gear_mc.paa",
				"lbt\Data\radio_mc.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_coy.paa",
				"lbt\Data\m203_co.paa",
				"lbt\Data\m203_gn.paa",
				"insignia"
			};
			uniformModel="\lbt\weapons";
		};
	};
	class lbt_medical_coy: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT COY (Medical)";
		picture="\lbt\UI\lbtcoy_ca.paa";
		model="\lbt\medical";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_coy.paa",
			"lbt\Data\gear_coy.paa",
			"lbt\Data\radio_coy.paa",
			"lbt\Data\shears_co.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_coy.paa",
				"lbt\Data\gear_coy.paa",
				"lbt\Data\radio_coy.paa",
				"lbt\Data\shears_co.paa",
				"lbt\Data\pouch_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\medical";
		};
	};
	class lbt_medical_od: lbt_medical_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT OD (Medical)";
		picture="\lbt\UI\lbtod_ca.paa";
		model="\lbt\medical";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_co.paa",
			"lbt\Data\gear_co.paa",
			"lbt\Data\radio_co.paa",
			"lbt\Data\shears_od.paa",
			"lbt\Data\pouch_co.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_co.paa",
				"lbt\Data\gear_co.paa",
				"lbt\Data\radio_co.paa",
				"lbt\Data\shears_od.paa",
				"lbt\Data\pouch_co.paa",
				"insignia"
			};
			uniformModel="\lbt\medical";
		};
	};
	class lbt_medical_aor1: lbt_medical_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT AOR1 (Medical)";
		picture="\lbt\UI\lbtaor1_ca.paa";
		model="\lbt\medical";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_aor1.paa",
			"lbt\Data\gear_aor1.paa",
			"lbt\Data\radio_aor1.paa",
			"lbt\Data\shears_co.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_aor1.paa",
				"lbt\Data\gear_aor1.paa",
				"lbt\Data\radio_aor1.paa",
				"lbt\Data\shears_co.paa",
				"lbt\Data\pouch_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\medical";
		};
	};
	class lbt_medical_aor2: lbt_medical_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT AOR2 (Medical)";
		picture="\lbt\UI\lbtaor2_ca.paa";
		model="\lbt\medical";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_aor2.paa",
			"lbt\Data\gear_aor2.paa",
			"lbt\Data\radio_aor2.paa",
			"lbt\Data\shears_od.paa",
			"lbt\Data\pouch_co.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_aor2.paa",
				"lbt\Data\gear_aor2.paa",
				"lbt\Data\radio_aor2.paa",
				"lbt\Data\shears_od.paa",
				"lbt\Data\pouch_co.paa",
				"insignia"
			};
			uniformModel="\lbt\medical";
		};
	};
	class lbt_medical_mc: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT MC (Medical)";
		picture="\lbt\UI\lbtmc_ca.paa";
		model="\lbt\medical";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_mc.paa",
			"lbt\Data\gear_mc.paa",
			"lbt\Data\radio_mc.paa",
			"lbt\Data\shears_co.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_mc.paa",
				"lbt\Data\gear_mc.paa",
				"lbt\Data\radio_mc.paa",
				"lbt\Data\shears_co.paa",
				"lbt\Data\pouch_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\medical";
		};
	};
	class lbt_comms_coy: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT COY (Comms)";
		picture="\lbt\UI\lbtcoy_ca.paa";
		model="\lbt\comms";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_coy.paa",
			"lbt\Data\gear_coy.paa",
			"lbt\Data\radio_coy.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_coy.paa",
				"lbt\Data\gear_coy.paa",
				"lbt\Data\radio_coy.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_co.paa",
				"insignia"
			};
			uniformModel="\lbt\comms";
		};
	};
	
	class lbt_comms_od: lbt_comms_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT OD (Comms)";
		picture="\lbt\UI\lbtod_ca.paa";
		model="\lbt\comms";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_co.paa",
			"lbt\Data\gear_co.paa",
			"lbt\Data\radio_co.paa",
			"lbt\Data\grenade_co.paa",
			"lbt\Data\pouch_co.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_co.paa",
				"lbt\Data\gear_co.paa",
				"lbt\Data\radio_co.paa",
				"lbt\Data\grenade_co.paa",
				"lbt\Data\pouch_co.paa",
				"insignia"
			};
			uniformModel="\lbt\comms";
			containerClass="Supply160";
			mass=50;
		};
	};
	class lbt_comms_aor1: lbt_comms_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT AOR1 (Comms)";
		picture="\lbt\UI\lbtaor1_ca.paa";
		model="\lbt\comms";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_aor1.paa",
			"lbt\Data\gear_aor1.paa",
			"lbt\Data\radio_aor1.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_aor1.paa",
				"lbt\Data\gear_aor1.paa",
				"lbt\Data\radio_aor1.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\comms";
		};
	};
	class lbt_comms_aor2: lbt_comms_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT AOR2 (Comms)";
		picture="\lbt\UI\lbtaor2_ca.paa";
		model="\lbt\comms";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_aor2.paa",
			"lbt\Data\gear_aor2.paa",
			"lbt\Data\radio_aor2.paa",
			"lbt\Data\grenade_co.paa",
			"lbt\Data\pouch_co.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_aor2.paa",
				"lbt\Data\gear_aor2.paa",
				"lbt\Data\radio_aor2.paa",
				"lbt\Data\grenade_co.paa",
				"lbt\Data\pouch_co.paa",
				"insignia"
			};
			uniformModel="\lbt\comms";
			containerClass="Supply160";
			mass=50;
			armor=50.5;
			passThrough=0.5;
		};
	};
	class lbt_comms_mc: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT MC (Comms)";
		picture="\lbt\UI\lbtmc_ca.paa";
		model="\lbt\comms";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_mc.paa",
			"lbt\Data\gear_mc.paa",
			"lbt\Data\radio_co.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_mc.paa",
				"lbt\Data\gear_mc.paa",
				"lbt\Data\radio_mc.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\comms";
		};
	};
	class lbt_light_od: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT OD (Light)";
		picture="\lbt\UI\lbtod_ca.paa";
		model="\lbt\light";
		
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_co.paa",
			"lbt\Data\gear_co.paa",
			"lbt\Data\radio_co.paa",
			"lbt\Data\grenade_co.paa",
			"lbt\Data\pouch_co.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_co.paa",
				"lbt\Data\gear_co.paa",
				"lbt\Data\radio_co.paa",
				"lbt\Data\grenade_co.paa",
				"lbt\Data\pouch_co.paa",
				"insignia"
			};
			uniformModel="\lbt\light";
			containerClass="Supply160";
			mass=50;
			armor=1;
			passThrough=0.1;
		};
	};
	class lbt_light_mc: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT MC (Light)";
		picture="\lbt\UI\lbtmc_ca.paa";
		model="\lbt\light";
		
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_mc.paa",
			"lbt\Data\gear_mc.paa",
			"lbt\Data\radio_co.paa",
			"lbt\Data\grenade_co.paa",
			"lbt\Data\pouch_co.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_mc.paa",
				"lbt\Data\gear_mc.paa",
				"lbt\Data\radio_co.paa",
				"lbt\Data\grenade_co.paa",
				"lbt\Data\pouch_co.paa",
				"insignia"
			};
			uniformModel="\lbt\light";
			containerClass="Supply160";
			mass=50;
			armor=1;
			passThrough=0.1;
		};
	};
	class lbt_light_aor1: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT AOR1 (Light)";
		picture="\lbt\UI\lbtaor1_ca.paa";
		model="\lbt\light";
		
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_aor1.paa",
			"lbt\Data\gear_aor1.paa",
			"lbt\Data\radio_aor1.paa",
			"lbt\Data\grenade_co.paa",
			"lbt\Data\pouch_co.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_aor1.paa",
				"lbt\Data\gear_aor1.paa",
				"lbt\Data\radio_aor1.paa",
				"lbt\Data\grenade_co.paa",
				"lbt\Data\pouch_co.paa",
				"insignia"
			};
			uniformModel="\lbt\light";
			containerClass="Supply160";
			mass=50;
			armor=1;
			passThrough=0.1;
		};
	};
	class lbt_light_aor2: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT AOR2 (Light)";
		picture="\lbt\UI\lbtaor2_ca.paa";
		model="\lbt\light";
		
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_aor2.paa",
			"lbt\Data\gear_aor2.paa",
			"lbt\Data\radio_aor2.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_aor2.paa",
				"lbt\Data\gear_aor2.paa",
				"lbt\Data\radio_aor2.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\light";
			containerClass="Supply160";
			mass=50;
			armor=1;
			passThrough=0.1;
		};
	};
	class lbt_light_coy: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT COY (Light)";
		picture="\lbt\UI\lbtcoy_ca.paa";
		model="\lbt\light";
		
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_coy.paa",
			"lbt\Data\gear_coy.paa",
			"lbt\Data\radio_coy.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_coy.paa",
				"lbt\Data\gear_coy.paa",
				"lbt\Data\radio_coy.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\light";
			containerClass="Supply160";
			mass=50;
			armor=1;
			passThrough=0.1;
		};
	};
	class lbt_fast_coy: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="[S4] LBT COY (Fast)";
		picture="\lbt\UI\lbtcoy_ca.paa";
		model="\lbt\fast";
		
		hiddenSelections[]=
		{
			"Camo",
			"Camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_coy.paa",
			"lbt\Data\gear_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_coy.paa",
				"lbt\Data\gear_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\fast";
			containerClass="Supply160";
			mass=50;
			armor=1;
			passThrough=0.1;
		};
	};	
	class lbt_pouchless_amcu: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="TBAS T1 (AMCU - Pouchless)";
		picture="\lbt\UI\lbtod_ca.paa";
		model="\lbt\pouchless";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_amcu.paa",
			"lbt\Data\gear_amcu.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_amcu.paa",
				"lbt\Data\gear_amcu.paa",
				"insignia"
			};
			uniformModel="\lbt\pouchless";
		};
	};
	class lbt_tl_amcu: lbt_tl_mc
	{
		author="Cunico";
		scope=2;
		displayName="TBAS T1 (AMCU - Team Lead)";
		picture="\lbt\UI\lbtcoy_ca.paa";
		model="\lbt\tl";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_amcu.paa",
			"lbt\Data\gear_amcu.paa",
			"lbt\Data\radio_co.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_amcu.paa",
				"lbt\Data\gear_amcu.paa",
				"lbt\Data\radio_coy.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\tl";
		};
	};
	class lbt_operator_amcu: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="TBAS T1 (AMCU - Operator)";
		picture="\lbt\UI\lbtcoy_ca.paa";
		model="\lbt\operator";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_amcu.paa",
			"lbt\Data\gear_amcu.paa",
			"lbt\Data\radio_coy.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_amcu.paa",
				"lbt\Data\gear_amcu.paa",
				"lbt\Data\radio_coy.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\operator";
		};
	};
	class lbt_weapons_amcu: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="TBAS T1 (AMCU - Weapons)";
		picture="\lbt\UI\lbtcoy_ca.paa";
		model="\lbt\weapons";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5",
			"Camo6",
			"Camo7"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_amcu.paa",
			"lbt\Data\gear_amcu.paa",
			"lbt\Data\radio_co.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"lbt\Data\m203_co.paa",
			"lbt\Data\m203_gn.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5",
				"Camo6",
				"Camo7"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_amcu.paa",
				"lbt\Data\gear_amcu.paa",
				"lbt\Data\radio_co.paa",
				"lbt\Data\grenade_co.paa",
				"lbt\Data\pouch_coy.paa",
				"lbt\Data\m203_co.paa",
				"lbt\Data\m203_gn.paa",
				"insignia"
			};
			uniformModel="\lbt\weapons";
		};
	};
	class lbt_medical_amcu: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="TBAS T1 (AMCU - Medical)";
		picture="\lbt\UI\lbtcoy_ca.paa";
		model="\lbt\medical";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_amcu.paa",
			"lbt\Data\gear_amcu.paa",
			"lbt\Data\radio_coy.paa",
			"lbt\Data\shears_co.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_amcu.paa",
				"lbt\Data\gear_amcu.paa",
				"lbt\Data\radio_coy.paa",
				"lbt\Data\shears_co.paa",
				"lbt\Data\pouch_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\medical";
		};
	};
	class lbt_comms_amcu: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="TBAS T1 (AMCU - Comms)";
		picture="\lbt\UI\lbtcoy_ca.paa";
		model="\lbt\comms";
		containerClass="Supply160";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_amcu.paa",
			"lbt\Data\gear_amcu.paa",
			"lbt\Data\radio_coy.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_amcu.paa",
				"lbt\Data\gear_amcu.paa",
				"lbt\Data\radio_coy.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_co.paa",
				"insignia"
			};
			uniformModel="\lbt\comms";
		};
	};
	class lbt_light_amcu: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="TBAS T1 (AMCU - Light)";
		picture="\lbt\UI\lbtcoy_ca.paa";
		model="\lbt\light";
		
		hiddenSelections[]=
		{
			"Camo",
			"Camo2",
			"Camo3",
			"Camo4",
			"Camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_amcu.paa",
			"lbt\Data\gear_amcu.paa",
			"lbt\Data\radio_coy.paa",
			"lbt\Data\grenade_coy.paa",
			"lbt\Data\pouch_coy.paa",
			"insignia"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2",
				"Camo3",
				"Camo4",
				"Camo5"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_amcu.paa",
				"lbt\Data\gear_amcu.paa",
				"lbt\Data\radio_coy.paa",
				"lbt\Data\grenade_coy.paa",
				"lbt\Data\pouch_coy.paa",
				"insignia"
			};
			uniformModel="\lbt\light";
			containerClass="Supply160";
			mass=50;
			armor=1;
			passThrough=0.1;
		};
	};
	class lbt_fast_amcu: lbt_pouchless_coy
	{
		author="Cunico";
		scope=2;
		displayName="TBAS T1 (AMCU - Fast)";
		picture="\lbt\UI\lbtcoy_ca.paa";
		model="\lbt\fast";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"lbt\Data\lbt_amcu.paa",
			"lbt\Data\gear_amcu.paa"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"Camo",
				"Camo2"
			};
			hiddenSelectionsTextures[]=
			{
				"lbt\Data\lbt_amcu.paa",
				"lbt\Data\gear_amcu.paa"
			};
			uniformModel="\lbt\fast";
			containerClass="Supply160";
			mass=50;
			armor=1;
			passThrough=0.1;
		};
	};
};
